# Use the official Nginx image as the base image
FROM nginx:stable-alpine

# Set the working directory inside the container
WORKDIR /usr/share/nginx/html

# Remove the default Nginx static assets
RUN rm -rf ./*

# Copy your frontend files into the working directory
COPY . .

# Expose port 80 to serve the application
EXPOSE 80

# Start the Nginx server
CMD ["nginx", "-g", "daemon off;"]
